- name: Update Prometheus Configuration
  template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Update Records file
  template:
    src: records.yml
    dest: /opt/prometheus/records.yml

- name: Update Instance Alerts file
  template:
    src: alerts.yml
    dest: /opt/prometheus/alerts.yml

- name: Update Application Alerts file
  template:
    src: appAlerts.yml
    dest: /opt/prometheus/appAlerts.yml

- name: Restart Prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: yes